keys:
  - &coconut age1srfkwm8rnmqdnnyq0t0x92fxmdk36qzp4lzdur0jfcttkhkjkflqs9wl9x
  - &berry age18lg4yvamkc77mv9ehxf62hjyne5tl05klw5a2mn7r6vnr72j7e3sd64qqd
  - &pi4 age1jqef99fafm6f9l5wwchj6kru226j6jyq48p9xxu45gzsjrhq0a8qy3ys8z
  - &plum age182r2c3s92x0uek8wx5zsvh9shnmt44ehnmddarl6wdza407wdqeqr550jx
  - &sho_coconut age1z7m0kfmkcmg7k5dvxpqkq5qan8ldgmw4kmuna44qtxre56h39uzq55g7lk
  - &sho_berry age1ahcp2hkfpnq29cnr6hntat3rctevvtzegkgnex0rwx77565h4alsmp8cmq
  - &sho_pi4 age1jp0wv8z8jyl3vhd3t2688g268z78dq39r6cue4fd7zmaazt04y7s6k43yl
  - &sho_plum age1hxug2vf8dwfjcszkr40lhdwm8zq9rgjysfepv33sf6nvyeh7ygmswd5hez
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *coconut
          - *berry
          - *pi4
          - *plum
          - *sho_coconut
          - *sho_berry
          - *sho_pi4
          - *sho_plum
