name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          github_access_token = github.com=${{ secrets.GITHUB_TOKEN }}
   
    - name: Check flake
      run: nix flake check --show-trace
    - name: Check devshell
      run: nix develop --show-trace
